

ALTER TABLE todos ADD COLUMN new_id UUID NULL;
UPDATE todos SET new_id = CAST(LPAD(TO_HEX(id), 32, '0') AS UUID);
ALTER TABLE todos DROP COLUMN id;
ALTER TABLE todos RENAME COLUMN new_id TO id;
ALTER TABLE todos ALTER COLUMN id SET NOT NULL;
